version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unconvert
    - unused

  exclusions:
    rules:
      # Test files can have repeated strings for readability
      - path: _test\.go
        linters:
          - goconst

      # Test files use hardcoded credentials for testing purposes
      - path: _test\.go
        linters:
          - gosec
        text: "G101"

      # CLI tools need to read user-specified config files
      - path: pkg/config/
        linters:
          - gosec
        text: "G304"

      # Temp file cleanup uses os.CreateTemp paths, not user input
      - path: pkg/argocd/helm\.go
        linters:
          - gosec
        text: "G703"

      # Temp file cleanup uses os.CreateTemp paths, not user input
      - path: pkg/helm/helm\.go
        linters:
          - gosec
        text: "G703"
