package main

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"

	"github.com/nebari-dev/nebari-infrastructure-core/internal/cli"
)

// generateCLIDocs writes one markdown page per nic command into outputDir,
// built from the same command tree the nic binary runs (internal/cli.NewRootCmd).
// doc.GenMarkdownTree walks the tree directly without ever calling
// Execute/ExecuteC, so cobra never attaches the completion command - there's
// nothing to filter out of the generated output.
func generateCLIDocs(outputDir string) error {
	if err := os.MkdirAll(outputDir, 0750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	rootCmd := cli.NewRootCmd()
	if err := doc.GenMarkdownTree(rootCmd, outputDir); err != nil {
		return err
	}

	return stripCobraDateFooters(outputDir)
}

// stripCobraDateFooters removes the "Auto generated by spf13/cobra on <date>"
// footer line from generated markdown files so the output is stable across runs.
func stripCobraDateFooters(dir string) (err error) {
	root, err := os.OpenRoot(dir)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := root.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil || d.IsDir() || !strings.HasSuffix(path, ".md") {
			return walkErr
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		rf, err := root.Open(rel)
		if err != nil {
			return err
		}
		content, err := io.ReadAll(rf)
		if cerr := rf.Close(); cerr != nil && err == nil {
			err = cerr
		}
		if err != nil {
			return err
		}

		lines := strings.Split(string(content), "\n")
		filtered := lines[:0]
		for _, line := range lines {
			if !strings.HasPrefix(line, "###### Auto generated by spf13/cobra on ") {
				filtered = append(filtered, line)
			}
		}

		wf, err := root.OpenFile(rel, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
		if err != nil {
			return err
		}
		_, err = wf.Write([]byte(strings.Join(filtered, "\n")))
		if cerr := wf.Close(); cerr != nil && err == nil {
			err = cerr
		}
		return err
	})
}
