package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateCLIDocsGeneratesExpectedFiles(t *testing.T) {
	tmpDir := t.TempDir()

	if err := generateCLIDocs(tmpDir); err != nil {
		t.Fatalf("generateCLIDocs: %v", err)
	}

	for _, name := range []string{
		"nic.md",
		"nic_deploy.md",
		"nic_destroy.md",
		"nic_validate.md",
		"nic_version.md",
		"nic_kubeconfig.md",
	} {
		if _, err := os.Stat(filepath.Join(tmpDir, name)); err != nil {
			t.Errorf("expected file %s not generated: %v", name, err)
		}
	}
}

func TestGenerateCLIDocsDeployFlagsDocumented(t *testing.T) {
	tmpDir := t.TempDir()

	if err := generateCLIDocs(tmpDir); err != nil {
		t.Fatalf("generateCLIDocs: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "nic_deploy.md")) //nolint:gosec
	if err != nil {
		t.Fatalf("read nic_deploy.md: %v", err)
	}

	for _, flag := range []string{"--file", "--dry-run", "--timeout", "--regen-apps"} {
		if !bytes.Contains(content, []byte(flag)) {
			t.Errorf("flag %s missing from nic_deploy.md", flag)
		}
	}
}

func TestGenerateCLIDocsExcludesCompletionCommandAndFooter(t *testing.T) {
	tmpDir := t.TempDir()

	if err := generateCLIDocs(tmpDir); err != nil {
		t.Fatalf("generateCLIDocs: %v", err)
	}

	entries, err := os.ReadDir(tmpDir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}

	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), "nic_completion") {
			t.Errorf("unexpected completion doc generated: %s", entry.Name())
		}

		content, err := os.ReadFile(filepath.Join(tmpDir, entry.Name())) //nolint:gosec
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		if bytes.Contains(content, []byte("Auto generated by spf13/cobra")) {
			t.Errorf("%s still contains the cobra date footer", entry.Name())
		}
	}
}
