package main

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var (
	gendocsOutputDir string

	gendocsCmd = &cobra.Command{
		Use:    "__gendocs",
		Short:  "Generate markdown reference documentation",
		Hidden: true,
		RunE:   runGendocs,
	}
)

func init() {
	gendocsCmd.Flags().StringVar(&gendocsOutputDir, "output-dir", "docs/reference/cli", "Directory to write generated markdown files")
	rootCmd.AddCommand(gendocsCmd)
}

func runGendocs(cmd *cobra.Command, args []string) error {
	if err := os.MkdirAll(gendocsOutputDir, 0750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	// Remove this command from rootCmd so it is excluded from the generated output.
	rootCmd.RemoveCommand(cmd)
	rootCmd.CompletionOptions.DisableDefaultCmd = true

	if err := doc.GenMarkdownTree(rootCmd, gendocsOutputDir); err != nil {
		return err
	}

	return stripCobraDateFooters(gendocsOutputDir)
}

// stripCobraDateFooters removes the "Auto generated by spf13/cobra on <date>"
// footer line from generated markdown files so the output is stable across runs.
func stripCobraDateFooters(dir string) (err error) {
	root, err := os.OpenRoot(dir)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := root.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil || d.IsDir() || !strings.HasSuffix(path, ".md") {
			return walkErr
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		rf, err := root.Open(rel)
		if err != nil {
			return err
		}
		content, err := io.ReadAll(rf)
		if cerr := rf.Close(); cerr != nil && err == nil {
			err = cerr
		}
		if err != nil {
			return err
		}

		lines := strings.Split(string(content), "\n")
		filtered := lines[:0]
		for _, line := range lines {
			if !strings.HasPrefix(line, "###### Auto generated by spf13/cobra on ") {
				filtered = append(filtered, line)
			}
		}

		wf, err := root.OpenFile(rel, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
		if err != nil {
			return err
		}
		_, err = wf.Write([]byte(strings.Join(filtered, "\n")))
		if cerr := wf.Close(); cerr != nil && err == nil {
			err = cerr
		}
		return err
	})
}
