package main

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"go.opentelemetry.io/otel"
)

var (
	gendocsOutputDir string

	gendocsCmd = &cobra.Command{
		Use:    "__gendocs",
		Short:  "Generate markdown reference documentation",
		Hidden: true,
		RunE:   runGendocs,
	}
)

func init() {
	gendocsCmd.Flags().StringVar(&gendocsOutputDir, "output-dir", "docs/reference/cli", "Directory to write generated markdown files")
}

func runGendocs(cmd *cobra.Command, args []string) error {
	ctx := cmd.Context()

	tracer := otel.Tracer("nebari-infrastructure-core")
	_, span := tracer.Start(ctx, "cmd.gendocs")
	defer span.End()

	if err := os.MkdirAll(gendocsOutputDir, 0750); err != nil {
		span.RecordError(err)
		return fmt.Errorf("create output directory: %w", err)
	}

	// Remove this command, plus the completion command cobra's ExecuteC attaches
	// to rootCmd before RunE ever runs, so neither shows up in the generated
	// output. Setting CompletionOptions.DisableDefaultCmd here is too late: the
	// completion command is already attached by the time this line executes.
	rootCmd.RemoveCommand(cmd)
	for _, c := range rootCmd.Commands() {
		if c.Name() == "completion" {
			rootCmd.RemoveCommand(c)
		}
	}

	if err := doc.GenMarkdownTree(rootCmd, gendocsOutputDir); err != nil {
		span.RecordError(err)
		return err
	}

	if err := stripCobraDateFooters(gendocsOutputDir); err != nil {
		span.RecordError(err)
		return err
	}
	return nil
}

// stripCobraDateFooters removes the "Auto generated by spf13/cobra on <date>"
// footer line from generated markdown files so the output is stable across runs.
func stripCobraDateFooters(dir string) (err error) {
	root, err := os.OpenRoot(dir)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := root.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil || d.IsDir() || !strings.HasSuffix(path, ".md") {
			return walkErr
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		rf, err := root.Open(rel)
		if err != nil {
			return err
		}
		content, err := io.ReadAll(rf)
		if cerr := rf.Close(); cerr != nil && err == nil {
			err = cerr
		}
		if err != nil {
			return err
		}

		lines := strings.Split(string(content), "\n")
		filtered := lines[:0]
		for _, line := range lines {
			if !strings.HasPrefix(line, "###### Auto generated by spf13/cobra on ") {
				filtered = append(filtered, line)
			}
		}

		wf, err := root.OpenFile(rel, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
		if err != nil {
			return err
		}
		_, err = wf.Write([]byte(strings.Join(filtered, "\n")))
		if cerr := wf.Close(); cerr != nil && err == nil {
			err = cerr
		}
		return err
	})
}
