package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra/doc"
)

func TestGendocsGeneratesExpectedFiles(t *testing.T) {
	tmpDir := t.TempDir()

	rootCmd.RemoveCommand(gendocsCmd)
	t.Cleanup(func() { rootCmd.AddCommand(gendocsCmd) })

	if err := doc.GenMarkdownTree(rootCmd, tmpDir); err != nil {
		t.Fatalf("GenMarkdownTree: %v", err)
	}

	for _, name := range []string{
		"nic.md",
		"nic_deploy.md",
		"nic_destroy.md",
		"nic_validate.md",
		"nic_version.md",
		"nic_kubeconfig.md",
	} {
		if _, err := os.Stat(filepath.Join(tmpDir, name)); err != nil {
			t.Errorf("expected file %s not generated: %v", name, err)
		}
	}
}

func TestGendocsDeployFlagsDocumented(t *testing.T) {
	tmpDir := t.TempDir()

	rootCmd.RemoveCommand(gendocsCmd)
	t.Cleanup(func() { rootCmd.AddCommand(gendocsCmd) })

	if err := doc.GenMarkdownTree(rootCmd, tmpDir); err != nil {
		t.Fatalf("GenMarkdownTree: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "nic_deploy.md")) //nolint:gosec
	if err != nil {
		t.Fatalf("read nic_deploy.md: %v", err)
	}

	for _, flag := range []string{"--file", "--dry-run", "--timeout", "--regen-apps"} {
		if !bytes.Contains(content, []byte(flag)) {
			t.Errorf("flag %s missing from nic_deploy.md", flag)
		}
	}
}

// TestGendocsEndToEndExcludesCompletionCommand runs the real __gendocs command
// through rootCmd.Execute, the only path that reproduces cobra attaching the
// completion command to rootCmd before RunE runs. Calling
// doc.GenMarkdownTree directly (as the tests above do) never attaches
// completion, which is why the completion-command regression this test
// guards against was invisible to the existing tests.
func TestGendocsEndToEndExcludesCompletionCommand(t *testing.T) {
	tmpDir := t.TempDir()

	t.Cleanup(func() {
		rootCmd.AddCommand(gendocsCmd)
		rootCmd.SetArgs(nil)
	})

	rootCmd.SetArgs([]string{"__gendocs", "--output-dir", tmpDir})
	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("Execute: %v", err)
	}

	entries, err := os.ReadDir(tmpDir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}

	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), "nic_completion") {
			t.Errorf("unexpected completion doc generated: %s", entry.Name())
		}

		content, err := os.ReadFile(filepath.Join(tmpDir, entry.Name())) //nolint:gosec
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		if bytes.Contains(content, []byte("Auto generated by spf13/cobra")) {
			t.Errorf("%s still contains the cobra date footer", entry.Name())
		}
	}
}
