apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: allow-recurring-job-while-volume-detached
  namespace: longhorn-system
  labels:
    app.kubernetes.io/managed-by: nebari-infrastructure-core
value: "{{ .LonghornAllowDetached }}"
