apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nebari-foundational
    app.kubernetes.io/managed-by: nebari-infrastructure-core
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foundational

  sources:
    - chart: gateway-helm
      repoURL: docker.io/envoyproxy
      targetRevision: v1.6.2
      helm:
        releaseName: envoy-gateway
        valueFiles:
          - $values/{{ if .GitPath }}{{ .GitPath }}/{{ end }}values/envoy-gateway/base.yaml
          - $values/{{ if .GitPath }}{{ .GitPath }}/{{ end }}values/envoy-gateway/overlays/*.yaml
        ignoreMissingValueFiles: true
    - repoURL: {{ .GitRepoURL }}
      targetRevision: {{ .GitBranch }}
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
