apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebari-operator
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nebari-foundational
    app.kubernetes.io/managed-by: nebari-infrastructure-core
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foundational

  source:
    repoURL: https://github.com/nebari-dev/nebari-operator
    targetRevision: HEAD
    path: dist/chart
    helm:
      releaseName: nebari-operator
      values: |
        image:
          repository: quay.io/nebari/nebari-operator
          pullPolicy: IfNotPresent
          tag: ""
        replicaCount: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        webhook:
          enabled: true
          port: 9443
        metrics:
          enabled: true
          port: 8080
        health:
          enabled: true
          port: 8081

  destination:
    server: https://kubernetes.default.svc
    namespace: nebari-operator-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
