apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nebari-foundational
    app.kubernetes.io/managed-by: nebari-infrastructure-core
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foundational

  sources:
    - chart: opentelemetry-collector
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.143.0
      helm:
        releaseName: opentelemetry-collector
        valueFiles:
          - $values/{{ if .GitPath }}{{ .GitPath }}/{{ end }}manifests/opentelemetry-collector/values.yaml
          - $values/{{ if .GitPath }}{{ .GitPath }}/{{ end }}manifests/opentelemetry-collector/overrides.yaml
    - repoURL: {{ .GitRepoURL }}
      targetRevision: {{ .GitBranch }}
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
