# Root App-of-Apps - manages all other ArgoCD Applications
# This is applied directly after GitOps bootstrap to hand control to ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebari-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nebari-foundational
    app.kubernetes.io/managed-by: nebari-infrastructure-core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foundational

  source:
    repoURL: {{ .GitRepoURL }}
    targetRevision: {{ .GitBranch }}
    path: {{ if .GitPath }}{{ .GitPath }}/{{ end }}apps
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'root.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
